// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReplyInMyVoice.Infrastructure.Data;

#nullable disable

namespace ReplyInMyVoice.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613040838_AddUserRewriteRateLimitWindows")]
    partial class AddUserRewriteRateLimitWindows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("AdminExternalAuthUserId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Action", "CreatedAt");

                    b.HasIndex("AdminExternalAuthUserId", "CreatedAt");

                    b.HasIndex("TargetUserId", "CreatedAt");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CurrentPeriodStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentPeriodUsage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsTest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Last4")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MonthlyQuota")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WebhookSecret")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("PlanTier");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKeyRateLimitWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("WindowStart");

                    b.HasIndex("ApiKeyId", "WindowStart")
                        .IsUnique();

                    b.ToTable("ApiKeyRateLimitWindows");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKeyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CostUsdEstimate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Endpoint");

                    b.HasIndex("RequestId");

                    b.HasIndex("ApiKeyId", "CreatedAt");

                    b.ToTable("ApiKeyUsages");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsentAcceptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalAuthUserId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("PaymentFailedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PaymentGraceEndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PaymentGraceReminderSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ExternalAuthUserId")
                        .IsUnique();

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasFilter("[StripeCustomerId] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.BillingSupportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RelatedPaymentIntentId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedPaymentIntentId")
                        .HasFilter("[RelatedPaymentIntentId] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("BillingSupportRequests");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.LearningFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommonTone")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagnosisTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<string>("FailureType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PrimaryDiagnosisTag")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PromotionRecommendation")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SampleRefs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scenario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CommonTone");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FailureType");

                    b.HasIndex("PrimaryDiagnosisTag");

                    b.HasIndex("PromotionRecommendation");

                    b.HasIndex("RunId");

                    b.HasIndex("Scenario");

                    b.HasIndex("Severity");

                    b.ToTable("LearningFindings");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.LearningRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<string>("DigestPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FindingCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MeasuredCount")
                        .HasColumnType("int");

                    b.Property<string>("PromotionDecision")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionDecision");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.ToTable("LearningRuns");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "LockedUntil");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.PromoCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreditsGranted")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayCode")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("GrantTtlDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("MaxRedemptionsGlobal")
                        .HasColumnType("int");

                    b.Property<int>("MaxRedemptionsPerUser")
                        .HasColumnType("int");

                    b.Property<int>("RedemptionCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PromoCodes", t =>
                        {
                            t.HasCheckConstraint("CK_PromoCodes_CreditsGranted_Positive", "[CreditsGranted] > 0");

                            t.HasCheckConstraint("CK_PromoCodes_GrantTtlDays_Positive", "[GrantTtlDays] > 0");

                            t.HasCheckConstraint("CK_PromoCodes_MaxRedemptionsGlobal_PositiveOrNull", "[MaxRedemptionsGlobal] IS NULL OR [MaxRedemptionsGlobal] > 0");

                            t.HasCheckConstraint("CK_PromoCodes_MaxRedemptionsPerUser_Minimum", "[MaxRedemptionsPerUser] >= 1");

                            t.HasCheckConstraint("CK_PromoCodes_RedemptionCount_NonNegative", "[RedemptionCount] >= 0");

                            t.HasCheckConstraint("CK_PromoCodes_ValidUntil_After_ValidFrom", "[ValidUntil] > [ValidFrom]");
                        });
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.PromoCodeRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("CreditsGranted")
                        .HasColumnType("int");

                    b.Property<Guid>("PromoCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RedeemIpHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("RedeemedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RewriteCreditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PromoCodeId");

                    b.HasIndex("RedeemIpHash");

                    b.HasIndex("RedeemedAt");

                    b.HasIndex("RewriteCreditId");

                    b.HasIndex("UserId");

                    b.HasIndex("PromoCodeId", "UserId")
                        .IsUnique();

                    b.ToTable("PromoCodeRedemptions");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.Referral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CreditedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RefereeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferrerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SignupIpHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId")
                        .IsUnique();

                    b.HasIndex("ReferrerId", "CreditedAt");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("UserId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UserId", "DeletedAt", "CreatedAt");

                    b.ToTable("RewriteAttempts");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteCanaryRollback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AdminEmailSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AdminEmailStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<double>("BaselineAverageSignalDrop")
                        .HasColumnType("float");

                    b.Property<string>("CanaryStrategyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ControlStrategyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("GithubIssueOpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GithubIssueStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("GithubIssueUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("LastCheckedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("RegressionPoints")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("RollingAverageSignalDrop")
                        .HasColumnType("float");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("WindowEndedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WindowRewrites")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("WindowStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ResolvedAt");

                    b.HasIndex("Scenario");

                    b.HasIndex("State");

                    b.HasIndex("CanaryStrategyVersion", "CreatedAt");

                    b.ToTable("RewriteCanaryRollbacks");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteCostLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ChangePoints")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("DraftAiLikePercent")
                        .HasColumnType("int");

                    b.Property<int>("DraftWordCount")
                        .HasColumnType("int");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("InputCharCount")
                        .HasColumnType("int");

                    b.Property<int>("InternalStrategies")
                        .HasColumnType("int");

                    b.Property<Guid?>("LearningSampleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ModelsUsedJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OpenAiCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("OpenAiInputTokens")
                        .HasColumnType("int");

                    b.Property<int>("OpenAiOutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ProviderCallsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectedCandidates")
                        .HasColumnType("int");

                    b.Property<int>("RepairCandidates")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("RewriteAiLikePercent")
                        .HasColumnType("int");

                    b.Property<int?>("RewriteWordCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SaplingCallCount")
                        .HasColumnType("int");

                    b.Property<int>("SaplingCharacters")
                        .HasColumnType("int");

                    b.Property<decimal>("SaplingCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StrategyVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TonePreset")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("TotalEstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("UsedEscalation")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Scenario");

                    b.HasIndex("Status");

                    b.HasIndex("TotalEstimatedCostUsd");

                    b.HasIndex("UserId");

                    b.HasIndex("StrategyVersion", "CreatedAt");

                    b.ToTable("RewriteCostLogs");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteCredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountConsumed")
                        .HasColumnType("int");

                    b.Property<int>("AmountGranted")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ExpiryReminderSentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("OriginalAmountGranted")
                        .HasColumnType("int");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<long?>("StripeAmountTotal")
                        .HasColumnType("bigint");

                    b.Property<string>("StripeCurrency")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("StripeEventId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("StripeReceiptUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("StripeSku")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StripeEventId")
                        .IsUnique()
                        .HasFilter("[StripeEventId] IS NOT NULL");

                    b.HasIndex("StripePaymentIntentId")
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("RewriteCredits");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteLearningSample", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CandidateSignals")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChangePoints")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiagnosisTags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DraftAiLikePercent")
                        .HasColumnType("int");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("InternalStrategies")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("MessageToReplyTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RejectedCandidates")
                        .HasColumnType("int");

                    b.Property<int>("RepairCandidates")
                        .HasColumnType("int");

                    b.Property<int?>("RewriteAiLikePercent")
                        .HasColumnType("int");

                    b.Property<string>("RewritePlanSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RewrittenText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoughDraftReply")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TonePreset")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Scenario");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("RewriteLearningSamples");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteProviderCall", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Characters")
                        .HasColumnType("int");

                    b.Property<Guid>("CostLogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("EstimatedCostUsd")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CostLogId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Provider");

                    b.HasIndex("Role");

                    b.ToTable("RewriteProviderCalls");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.StrategyCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<Guid>("FindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkedCommitHash")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PatchAction")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("PatchTarget")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatchText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedChangeSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredEval")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RequiredRegressionTest")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Scenario")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FindingId");

                    b.HasIndex("PatchTarget");

                    b.HasIndex("RiskLevel");

                    b.HasIndex("Scenario");

                    b.HasIndex("Status");

                    b.ToTable("StrategyCandidates");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.StripeEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("EventId");

                    b.HasIndex("Status", "LockedUntil");

                    b.ToTable("StripeEvents");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.StripeInvoice", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<long>("AmountDue")
                        .HasColumnType("bigint");

                    b.Property<long>("AmountPaid")
                        .HasColumnType("bigint");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("HostedInvoiceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("InvoicePdf")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("NextPaymentAttempt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PeriodEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PeriodStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SubscriptionId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("StripeInvoices");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.StripeReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountMismatchCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GrantButNoPaymentCount")
                        .HasColumnType("int");

                    b.Property<int>("PaidButNoGrantCount")
                        .HasColumnType("int");

                    b.Property<int>("PurchaseGrantCount")
                        .HasColumnType("int");

                    b.Property<string>("ReportJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StripePaymentCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt");

                    b.HasIndex("WindowStart", "WindowEnd");

                    b.ToTable("StripeReconciliationRuns");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UsagePeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("PeriodEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<DateTimeOffset?>("PeriodStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("QuotaLimit")
                        .HasColumnType("int");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("UsagePeriods");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UsageReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RewriteAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RewriteCreditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("UsagePeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RewriteAttemptId")
                        .IsUnique();

                    b.HasIndex("RewriteCreditId");

                    b.HasIndex("UsagePeriodId");

                    b.HasIndex("Status", "ExpiresAt");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("UsageReservations");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UserRewriteRateLimitWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("WindowStart");

                    b.HasIndex("UserId", "WindowStart")
                        .IsUnique();

                    b.ToTable("UserRewriteRateLimitWindows");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RewriteAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RewriteAttemptId");

                    b.HasIndex("ApiKeyId", "RewriteAttemptId")
                        .IsUnique();

                    b.HasIndex("Status", "LockedUntil");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKeyRateLimitWindow", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.ApiKey", "ApiKey")
                        .WithMany("RateLimitWindows")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKeyUsage", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.ApiKey", "ApiKey")
                        .WithMany("ApiKeyUsages")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.BillingSupportRequest", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany("BillingSupportRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.LearningFinding", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.LearningRun", "Run")
                        .WithMany("Findings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.PromoCodeRedemption", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.PromoCode", "PromoCode")
                        .WithMany("Redemptions")
                        .HasForeignKey("PromoCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoCode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.Referral", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "Referrer")
                        .WithMany()
                        .HasForeignKey("ReferrerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteAttempt", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.ApiKey", "ApiKey")
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany("RewriteAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteCostLog", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteCredit", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteLearningSample", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteProviderCall", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.RewriteCostLog", "CostLog")
                        .WithMany("ProviderCalls")
                        .HasForeignKey("CostLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostLog");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.StrategyCandidate", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.LearningFinding", "Finding")
                        .WithMany("Candidates")
                        .HasForeignKey("FindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Finding");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.StripeInvoice", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UsagePeriod", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany("UsagePeriods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UsageReservation", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.RewriteAttempt", "RewriteAttempt")
                        .WithOne("Reservation")
                        .HasForeignKey("ReplyInMyVoice.Domain.Entities.UsageReservation", "RewriteAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReplyInMyVoice.Domain.Entities.RewriteCredit", "RewriteCredit")
                        .WithMany()
                        .HasForeignKey("RewriteCreditId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReplyInMyVoice.Domain.Entities.UsagePeriod", "UsagePeriod")
                        .WithMany("Reservations")
                        .HasForeignKey("UsagePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany("UsageReservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RewriteAttempt");

                    b.Navigation("RewriteCredit");

                    b.Navigation("UsagePeriod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UserRewriteRateLimitWindow", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.WebhookDelivery", b =>
                {
                    b.HasOne("ReplyInMyVoice.Domain.Entities.ApiKey", "ApiKey")
                        .WithMany("WebhookDeliveries")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReplyInMyVoice.Domain.Entities.RewriteAttempt", "RewriteAttempt")
                        .WithMany()
                        .HasForeignKey("RewriteAttemptId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("RewriteAttempt");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.ApiKey", b =>
                {
                    b.Navigation("ApiKeyUsages");

                    b.Navigation("RateLimitWindows");

                    b.Navigation("WebhookDeliveries");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("BillingSupportRequests");

                    b.Navigation("RewriteAttempts");

                    b.Navigation("UsagePeriods");

                    b.Navigation("UsageReservations");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.LearningFinding", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.LearningRun", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.PromoCode", b =>
                {
                    b.Navigation("Redemptions");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteAttempt", b =>
                {
                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.RewriteCostLog", b =>
                {
                    b.Navigation("ProviderCalls");
                });

            modelBuilder.Entity("ReplyInMyVoice.Domain.Entities.UsagePeriod", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
